---
- name: Deploy Ceph using tripleo-operator-ansible modules
  gather_facts: false
  hosts: localhost
  collections:
    - tripleo.operator
  vars:
    mkspec: false
    user: false
    deploy: true
    spec: /home/stack/xena/standalone/ceph_spec.yaml
    osd_spec: /home/stack/xena/standalone/osd_spec.yaml
    deployed_ceph_output: /home/stack/xena/standalone/deployed_ceph.yaml
    container_image_prepare: /home/stack/containers-prepare-parameter.yaml
    initial_ceph_conf: /home/stack/xena/standalone/initial_ceph.conf
    stack: standalone
    mon_ip: 192.168.122.252
  tasks:
    - when: mkspec
      block:
        - name: Create Ceph Spec
          include_role:
            name: tripleo_ceph_spec
          vars:
            tripleo_ceph_spec_debug: true
            tripleo_ceph_spec_generate_scripts: true
            tripleo_ceph_spec_overwrite: true
            tripleo_ceph_spec_standalone: true
            tripleo_ceph_spec_mon_ip: "{{ mon_ip }}"
            tripleo_ceph_spec_stack: "{{ stack }}"
            tripleo_ceph_spec_file: "{{ spec }}"
            tripleo_ceph_spec_osd_spec: "{{ osd_spec }}"
        - debug:
            msg: "{{ tripleo_ceph_spec_result }}"
    - when: user
      block:
        - name: Create user
          include_role:
            name: tripleo_ceph_user
          vars:
            tripleo_ceph_user_spec: "{{ spec }}"
            tripleo_ceph_user_enable: enable
            tripleo_ceph_user_stack: "{{ stack }}"
            tripleo_ceph_user_debug: true
            tripleo_ceph_user_generate_scripts: true
            tripleo_ceph_user_generate_scripts_only: false
            tripleo_ceph_user_standalone: true
        - debug:
            msg: "{{ tripleo_ceph_user_result }}"
    - when: deploy
      block:
        - name: Create initial ceph.conf
          copy:
           dest: "{{ initial_ceph_conf }}"
           content: |
             # passing initial conf has side effect of not
             # setting public/cluster_networks which is good
             # for standlone as ctlplane network is default
             # but it is not yet configured
             [global]
             osd pool default size = 1
             [mon]
             mon_warn_on_pool_no_redundancy = false
        - name: Deploy Ceph
          include_role:
            name: tripleo_ceph_deploy
          vars:
            tripleo_ceph_deploy_standalone: true
            tripleo_ceph_deploy_single_host_defaults: true
            tripleo_ceph_deploy_skip_user_create: true
            tripleo_ceph_deploy_skip_hosts_config: true
            tripleo_ceph_deploy_skip_container_registry_config: true
            tripleo_ceph_deploy_mon_ip: "{{ mon_ip }}"
            tripleo_ceph_deploy_spec: "{{ spec }}"
            tripleo_ceph_deploy_stack: "{{ stack }}"
            tripleo_ceph_deploy_config: "{{ initial_ceph_conf }}"
            tripleo_ceph_deploy_output: "{{ deployed_ceph_output }}"
            tripleo_ceph_deploy_cephadm_extra_args: "--log-to-file --skip-prepare-host"
            tripleo_ceph_deploy_force: true
            tripleo_ceph_deploy_become: true
            tripleo_ceph_deploy_overwrite: true
            tripleo_ceph_deploy_debug: true
            tripleo_ceph_deploy_generate_scripts: true
            tripleo_ceph_deploy_generate_scripts_only: false
        - debug:
            msg: "{{ tripleo_ceph_deploy_result }}"
