---
- name: Deploy Ceph using tripleo-operator-ansible modules
  gather_facts: false
  hosts: undercloud
  collections:
    - tripleo.operator
  vars:
    metal: /home/stack/xena/external/deployed-metal-ceph-e.yaml
    roles: /home/stack/xena/external/ceph_roles.yaml
    output: /home/stack/xena/external/ceph_spec.yaml
    stack: ceph-e
  tasks:
    - name: Create Ceph Spec
      include_role:
        name: tripleo_ceph_spec
      vars:
        tripleo_ceph_spec_debug: True
        tripleo_ceph_spec_deployed_baremetal: "{{ metal }}"
        tripleo_ceph_spec_stack: "{{ stack }}"
        tripleo_ceph_spec_roles_file: "{{ roles }}"
        tripleo_ceph_spec_file: "{{ output }}"
    - debug:
        msg: "{{ tripleo_ceph_spec_result }}"
